apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: mysc
  volumeMode: Filesystem
  hostPath:
    path: /data/mypv
  persistentVolumeReclaimPolicy: Recycle
