stages:
  - maven:verify
  - docker:build
  - deploy

maven_verify_job:
  image: maven:3.8.8-eclipse-temurin-8
  stage: maven:verify
  script:
    - mvn clean verify
  artifacts:
    when: on_success
    paths:
      - "target/*.jar"

docker_build_job:
  stage: docker:build
  needs:
    - maven_verify_job
  script:
    - docker build -t $CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_SHA . 
    
deploy_job:
  stage: deploy
  needs:
    - docker_build_job
  before_script:
    - if [[ "$(docker ps --filter "name=springapp" --format '{{.Names}}')" == "springapp" ]]; then  docker rm -f springapp;  fi
  script:
    - docker run --name "springapp" -d -p 8080:8080 $CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_SHA