name: Ejercicio 2 - Build and Publish an image into GH Container Registry

on:
  workflow_dispatch:
    inputs:
      project:
        description: 'Project to build and publish'
        type: choice
        required: true
        default: 'hangman-front'
        options:
          - 'hangman-front'
          - 'hangman-api'

env:
  REGISTRY: ghcr.io

jobs:
  docker-publish-job:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
    
    steps:
      - uses: actions/checkout@v4

      - name: Get current date
        id: current_date
        run: echo "::set-output name=date::$(date +'%Y%m%d%H%M')"
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ inputs.project }}
          tags: type=raw,value=latest-${{ steps.current_date.outputs.date }},enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
      
      - name: Build the image and push to Github container registry
        uses: docker/build-push-action@v5
        with:
          context: ./03-ci-cd/03-github-actions/${{ inputs.project }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}