name: Ejercicio 3 - Run E2E tests

on:
    workflow_dispatch:
        inputs:
            api_version:
                description: 'API image version to use'
                type: string
                required: true
            front_version:
                description: 'Front image version to use'
                type: string
                required: true

env:
    REGISTRY: ghcr.io
    API_VERSION: ${{ inputs.api_version }}
    FRONT_VERSION: ${{ inputs.front_version }}

jobs:
    e2e-job:
        runs-on: ubuntu-latest
        steps:
            - name: Check inputs
              shell: bash
              run: |
                regex="^[a-z0-9]+([_-][a-z0-9]+)*$"
                if [[ $API_VERSION =~ $regex  && $FRONT_VERSION =~ $regex ]]; then
                  echo "The format of both versions is correct."
                else
                  echo "The format of one or both versions is incorrect. Please double check them."
                  exit 1
                fi
                
            - uses: actions/checkout@v4

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                registry: ${{ env.REGISTRY }}
                username: ${{ github.repository_owner }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Start API and Front services
              run: |
                docker run -d -p 3001:3000 ${{ env.REGISTRY }}/danielfajardo/hangman-api:${{ env.API_VERSION }}
                docker run -d -p 8080:8080 -e API_URL=http://localhost:3001 ${{ env.REGISTRY }}/danielfajardo/hangman-front:${{ env.FRONT_VERSION }}
            
            - name: Run e2e tests
              uses: cypress-io/github-action@v6
              with:
                working-directory: ./03-ci-cd/03-github-actions/hangman-e2e/e2e
